# Generated by Django 3.2.9 on 2021-12-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(null=True, unique=True)),
                ('image_links', models.IntegerField(null=True)),
                ('attachment_links', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
