# Generated by Django 3.2.9 on 2021-12-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_excelfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
