# Generated by Django 3.2.9 on 2021-12-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211216_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readupdate',
            name='sku',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
