# Generated by Django 3.2.9 on 2021-12-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_readupdate_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readupdate',
            name='attachment_links',
            field=models.CharField(max_length=3072, null=True),
        ),
    ]
