# Generated by Django 3.2.9 on 2021-12-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211216_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readupdate',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='readupdate',
            name='s3_1',
        ),
    ]
