# Generated by Django 3.2.9 on 2021-12-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_person_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
