# Generated by Django 3.2.9 on 2021-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_person_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
