# Generated by Django 3.2.9 on 2021-12-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20211212_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
