# Generated by Django 3.2.9 on 2021-12-13 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20211213_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 9, 22, 33, 347924)),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 9, 22, 33, 347924)),
        ),
    ]
