# Generated by Django 3.2.9 on 2021-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20211213_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=750, null=True)),
                ('image_links', models.CharField(max_length=750, null=True)),
                ('attachment_links', models.CharField(max_length=750, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
