# Generated by Django 3.2.9 on 2021-12-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20211214_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readupdate',
            old_name='SKU',
            new_name='sku',
        ),
    ]
