# Generated by Django 3.2.9 on 2021-12-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20211215_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readupdate',
            name='attachment_links',
            field=models.CharField(max_length=3500, null=True),
        ),
        migrations.AlterField(
            model_name='readupdate',
            name='image_links',
            field=models.CharField(max_length=3500, null=True),
        ),
    ]
