# Generated by Django 3.2.9 on 2021-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20211215_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readupdate',
            name='attachment_links',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='readupdate',
            name='image_links',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='readupdate',
            name='sku',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
